import numpy as np
marks=np.array([[60,70,80],[70,80,90],[70,80,60]])
print(marks)
print(np.median(marks))
print("shape:",marks.shape)
result=np.median(marks,axis=1)
print(result)
print("result:",result.shape)
result1=np.median(marks,axis=0)
print(result1)
print("result:",result1.shape)